### ISSUE TITLE
博客文章链接路径出现“/post/undefined/”

### ISSUE THREAD

**Issue by zsdycs** [jiehua1995/blog#1]
hi~ @jiehua1995 

**你的博客出现问题啦。** 

## 影响范围
所有 2019 年的文章。😵 
目前只有 2020 年的两篇文章的链接可用。

## 记录
1. 地址 [blog.jiehua1995.xyz/](https://blog.jiehua1995.xyz/)
2. 在使用或未使用梯子访问均是如此。
3. 尝试过清除浏览器缓存访问，无效。🤖

PS：[立人楼离别事记](https://music.163.com/#/song?id=491711110) 写得真好！  
看着你是学的生物哇，怎么看着像写代码的哇，哈哈哈哈😄

**Comment by jiehua1995** [comment]
😄 谢谢提醒！
### 原因
我刚去查了一下，是因为我把站点设置改成了`permalink: post/:urlname/`
有些旧的文章里我忘了加上urlname这个标注。
### 解决
我已经给旧的文章都加了urlname标注，目前都可以正常访问了。

PS：谢谢夸奖呀~那首歌是当时毕业时候写给班级MV的主题曲。
主业是生物啦，但是业余对前端比较感兴趣哈哈哈。
